apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: busybox
    name: multi-pod1
    command: ["bin/sh", "-c", "echo hello; sleep 3600"]  
  - image: busybox
    name: multi-pod2
    command: ["bin/sh", "-c", "echo hello; sleep 3600"] 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
