apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app1
  name: app1
spec:
  containers:
  - args:
    - echo 
    - date 
    image: busybox 
    name: app1cont
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
