apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apple-deploy
  name: apple-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apple-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apple-deploy
    spec:
      containers:
      - image: nginx
        name: apple-bin
        resources:
          requests:
            memory: "15Mi"
          limits:
            memory: "30Mi"
