apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bash-pod
  name: bash-pod
spec:
  containers:
  - image: bash
    name: bash-pod
    command: ["bin/sh", "-c", "hostname > /tmp/hostname && sleep 1d"]  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
