apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  containers:
  - image: busybox
    name: busy
    command: ["bin/sh", "-c", "echo hello world"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
