apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cap
  name: nginx-cap
spec:
  containers:
  - image: nginx
    name: nginx-capi
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
