apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy03
  name: deploy03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy03
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy03
    spec:
      containers:
      - image: nginx:v2
        name: nginx
        resources: {}
status: {}
