apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: devbox
  name: devbox
spec:
  volumes:
  - name: volume2
    configMap:
      name: devconfig 
      items:
      - key: sdk.cfg
        path: sdk.cfg
  - name: volume1
    configMap:
      name: devconfig
      items:
      - key: language
        path: value.txt
  containers:
  - image: busybox
    name: devbox
    command: ["bin/sh", "-c", "sleep 3600"]  
    volumeMounts:
    - name: volume2
      mountPath: /var/dev-sdk/config/
    - name: volume1
      mountPath: /var/dev-sdk/lang/golang/version/
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
