apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: exam-pod-blue
  name: exam-pod-blue
  namespace: study
spec:
  containers:
  - image: $image 
    name: exam-pod
    env:
    - name: image_name
      value: santhosh
    ports:
    - containerPort: $PORT
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
