apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fsgroup-pod
  name: fsgroup-pod
spec:
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  securityContext:
    fsGroup: 2000
  containers:
  - image: nginx
    name: fsgroup-pod
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
