apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grapes
  name: grapes
spec:
  containers:
  - image: busybox
    name: grapes
    command: ["bin/sh", "-c", "echo 'I am ape for grapes'; sleep 3600"]  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
