apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      color: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        color: green
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80
       volumeMounts:
         - mountPath: /usr/share/nginx/html/index.html
           name: nginx-conf
           subPath: index.html
     volumes:
        - name: nginx-conf
          configMap:
            name: config-green
