apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: haproxy
  name: haproxy
spec:
  volumes:
  - name: config-volume
    configMap:
      name: ha-config
  containers:
  - image: haproxy
    name: haproxy
    ports:
    - containerPort: 60
    volumeMounts:
      - name: config-volume
        mountPath: /usr/local/etc/haproxy  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
