apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-nginx
  name: multi-nginx
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', "echo 'Santhosh Thomas here' >> /var/output/index.html"]
    volumeMounts:
    - mountPath: /var/output
      name: my-volume  
  containers:
  - image: nginx
    name: multi-nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume  
    resources: {}
  volumes:
  - name: my-volume
    emptyDir: {}    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
