apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  volumes:
  - name: pod-volume
    emptyDir: {}
  initContainers:
  - name: init-myservice
    image: busybox
    volumeMounts:
    - mountPath: /work-dir
      name: pod-volume  
    command: ['sh', '-c', "wget -O /work-dir/index.html http://neverssl.com/online"]
  containers:
  - image: nginx
    name: multi
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pod-volume  
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
