apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mybusybox
  name: mybusybox
  namespace: "140"
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - ls;sleep 3600;
    image: busybox
    name: mybusybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
