apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-configmap
  name: nginx-configmap
spec:
  volumes:
  - name: config-volume
    configMap:
      name: another-config
  containers:
  - image: nginx
    name: nginx-configmap
    volumeMounts:
    - name: config-volume
      mountPath: /also/a/path  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
