apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-probs
  name: nginx-probs
spec:
  containers:
  - image: nginx
    name: nginx-probs
    env:
    - name: liveness-port
      value: "80"  
    ports:    
    - name: $(liveness-port)
      containerPort: 80
      
