apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    version: v1
  name: nginx-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    version: v2
  type: NodePort
status:
  loadBalancer: {}
