apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: hello
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: hello
    spec:
      completions: 1
      activeDeadlineSeconds: 22  
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: hello
            command: ["bin/sh", "-c", "date"]  
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: 22  
status: {}
