apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plumpod
  name: plumpod
  namespace: plum
spec:
  containers:
  - image: nginx 
    name: plumpod
    readinessProbe:
      exec:
        command:
        - touch
        - /tmp/plumpplum
      initialDelaySeconds: 3
      periodSeconds: 6  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
