apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainerpod
  name: multicontainerpod
  namespace: ggckad-s2
spec:
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: multicontainerpod1
    securityContext:
      runAsUser: 1000  
      runAsGroup: 3000  
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: multicontainerpod2      
    securityContext:
      runAsUser: 2000 
      runAsGroup: 3000  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
