apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bash
  name: bash
spec:
  volumes:
  - name: foo
    secret:
      secretName: secret1
  containers:
  - image: bash
    name: bash
    command: ["bin/sh", "-c", "sleep 3600"]
    envFrom:
    - configMapRef:
        name: test-cm
    volumeMounts:
    - name: foo
      mountPath: "/tmp/secret1"
      readOnly: true  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never 
status: {}
