apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k8s-challenge-3"
