apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-test
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv" 
