apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strawberry-pvc
  namespace: straw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5M
  storageClassName: exam
