apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: question-thirteen-pod
  name: question-thirteen-pod
  namespace: ggckad-s4
spec:
  containers:
  - image: kubegoldenguide/question-thirteen
    name: question-thirteen-pod
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60 
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 60    
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
