apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: question-5
  name: question-5
  namespace: ggckad-s5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: question-5
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
