apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "100Gi"
        cpu: "0.5"  
      limits:
        memory: "200Gi"    
        cpu: "1"  
