apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: roll
spec:
  completions: 8
  backoffLimit: 11  
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: kodekloud/throw-dice
        name: roll
        resources: {}
      restartPolicy: Never
status: {}
