apiVersion: v1
kind: ResourceQuota
metadata:
    name: pods-high
spec:
  hard:
    cpu: "1000"
    memory: 200Mi
    pods: "2"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["high"]
