apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sa-busybox
  name: sa-busybox
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: sa-busybox
  serviceAccountName: admin
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
