apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secpod1
  name: secpod1
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: secpod1
    securityContext:
      runAsUser: 3000
      runAsGroup: 4000  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
