apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    func: webFrontEnd
  name: cherry
  namespace: one
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: something
  type: NodePort
status:
  loadBalancer: {}
