apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testcm
  name: testcm
spec:
  volumes:
  - name: config-volume
    configMap:
      name: anotherconfig
  containers:
  - image: nginx
    name: testcm
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
