apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp
  name: tmp
spec:
  containers:
  - env:
    - name: USER
      value: SAN
    image: busybox
    name: tmp
    command: ["/bin/sh", "-c", "echo $USER"]  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
