apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu03
  name: ubuntu03
  namespace: 50quest
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - date -s 'date'
    image: ubuntu
    name: ubuntu03
    securityContext:
      capabilities:
        add: ["SYS_TIME"]  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
