apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v2
  name: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v2
        svclabel: frontend  
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
