apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: watermelonslice
  name: watermelonslice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: watermelonslice
  strategy: {}
  template:
    metadata:
      labels:
        app: watermelonslice
        run: watermelon
      name: watermelon
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: watermelon
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: docker-desktop
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30

