apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cronjob-name
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cronjob-name
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: bash
            name: cronjob-name
            resources: {}
          restartPolicy: OnFailure
  schedule: 1 * * * *
status: {}
